version: '3'

services:

  outer:
    container_name: outer
    env_file: .env
    image: nginxproxy/nginx-proxy:dev
    labels:
      - "com.github.jrcs.letsencrypt_nginx_proxy_companion.nginx_proxy=true"
    ports:
      - "80:80"
      #- "443:443"
    restart: always
    environment:
      #- LETSENCRYPT_HOST=se-services.informatik.uos.de
      #- DEFAULT_HOST=outer.bar.com
      - DEFAULT_HOST=${HOST}
      - DHPARAM_GENERATION=false
    logging:
      driver: local #or "none" or "local"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro # allow to read running dockers
      - ./Proxy/conf.d/unrestricted_size.conf:/etc/nginx/conf.d/unrestricted_size.conf
      #- ./nginx/test:/etc/nginx/conf.d # to see the config output
      #- ./extraVolumes/certs:/etc/nginx/certs:ro
      #- ./extraVolumes/vhosts:/etc/nginx/vhost.d
      #- ./extraVolumes/html:/usr/share/nginx/html
      #- ./zerossl/certificate.crt:/etc/nginx/certs/se-services.informatik.uos.de.crt:ro
      #- ./zerossl/private.key:/etc/nginx/certs/se-services.informatik.uos.de.key:ro
    networks:
      - reverse-proxy

  app:
    container_name: outer_app
    image: jwilder/whoami
    env_file: .env
    environment:
      - VIRTUAL_HOST=${HOST}
      - LETSENCRYPT_HOST=${HOST}
      - VIRTUAL_PATH=/whoami
      - VIRTUAL_DEST=/
    networks:
      - reverse-proxy

networks:
  reverse-proxy:
    name: topDomainProxy
